services:
  - type: web_service
    name: expense-tracker-backend
    env: python
    root: backend
    plan: starter
    branch: main
    runtime: python-3.11.12
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
